Cenv/Projet/Home/urls.py
# rendez/urls.py
from django.urls import path
from .views import book_appointment,appointment_success

urlpatterns = [
    path('book-appointment/', book_appointment, name='book_appointment'),
   path('appointment-success/', appointment_success, name='appointment_success'),

    # autres URL...
]

Cenv/Projet/Projet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from Home import views as home_views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('',include('lead.urls')),
    path('',include('profils.urls')),
    path('', include('Rendez.urls')),
    path('',include('reports.urls')),
    path('',include('communication.urls')),
    path('',include('notification.urls')),
    path('',include('member_management.urls')),
    path('',include('campaigns.urls')),
    path('analyse/', include('analytics.urls')),
    #path('',include('googleAds1.urls')),
    path('admin/', admin.site.urls),
  

   #  path('',include('lead.urls')),
 
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
   path('book-appointment/', home_views.book_appointment, name='book_appointment'),
   path('appointment-success/', home_views.appointment_success, name='appointment_success'),  
  
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cenv/Projet/reports/urls.py
from django.urls import path
from . import views
from .views import export_data


urlpatterns = [
    path('reports/', views.report_view, name='report_dashboard'),
    path('reports/<int:report_id>/', views.report_view, name='report_detail'),
    path('export/<str:format>/', export_data, name='export_data'),
     path('reports/history/', views.report_view, name='report_history'),
]

Cenv/Projet/reports/models.py
from django.db import models

# Create your models here.
from django.db import models
#from django.contrib.auth.models import User
from datetime import date, datetime
import json
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Report(models.Model):
    REPORT_TYPE_CHOICES = [
        ('conversion', 'Rapport de Conversion'),
        ('campaign_performance', 'Rapport de Performance des Campagnes'),
        ('interaction', 'Rapport de Suivi des Interactions'),
    ]
     
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    report_type = models.CharField(max_length=100, choices=REPORT_TYPE_CHOICES)
    filters = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField(default='')
   
    def _str_(self):
        return f"{self.title} ({self.get_report_type_display()})"
    

    def filters_summary(self):
        if not self.filters:
            return "Aucun filtre appliqué"

        def convert(value):
            if isinstance(value, (datetime, date)):
                return value.strftime('%Y-%m-%d')  # Convertir en chaîne de caractères
            return value
        
        summary = []
        for key, value in self.filters.items():
            if isinstance(value, list):
                value = ', '.join(map(str, value))
            elif isinstance(value, (datetime, date)):
                value = convert(value)
            summary.append(f"{key.replace('_', ' ').capitalize()}: {value}")
        return "; ".join(summary)

Cenv/Projet/reports/forms.py
from django import forms
from .models import Report
from datetime import datetime
from datetime import date, datetime


class ReportForm(forms.ModelForm):
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    category = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Report
        fields = ['title', 'content', 'report_type']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5}),
        }

    def save(self, commit=True):
        report = super().save(commit=False)
        filters = {
            'start_date': self.cleaned_data.get('start_date'),
            'end_date': self.cleaned_data.get('end_date'),
            'category': self.cleaned_data.get('category')
        }

        # Convert date fields to string if they are not None
        filters = {k: (v.strftime('%Y-%m-%d') if isinstance(v, (datetime, date)) else v) for k, v in filters.items() if v is not None}
        
        report.filters = filters
        if commit:
            report.save()
        return report

Cenv/Projet/reports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReportForm
from .models import Report
import io
#import pandas as pd
import openpyxl
from lead.models import Lead
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.http import HttpResponse, JsonResponse

def report_view(request, report_id=None):
    if report_id:
        # Affichage des détails d'un rapport spécifique
        report = get_object_or_404(Report, id=report_id)
        return render(request, 'reports/report_detail.html', {'report': report})

    report_type = request.GET.get('report_type')

    if report_type in ['conversion', 'campaign_performance', 'interaction']:
        if request.method == 'POST':
            form = ReportForm(request.POST)
            if form.is_valid():
                report = form.save(commit=False)
                report.created_by = request.user
                report.report_type = report_type
                report.save()
                return redirect('report_dashboard')
        else:
            form = ReportForm()

        return render(request, 'reports/report_form.html', {
            'form': form,
            'report_type': {
                'conversion': 'Rapport de Conversion',
                'campaign_performance': 'Rapport de Performance des Campagnes',
                'interaction': 'Rapport de Suivi des Interactions'
            }.get(report_type, 'Rapport')
        })

    if request.GET.get('action') == 'history':
        reports = Report.objects.filter(created_by=request.user)
        return render(request, 'reports/report_history.html', {'reports': reports})

    report_options = [
        {'name': 'Rapport de Conversion', 'url': '?report_type=conversion'},
        {'name': 'Rapport de Performance des Campagnes', 'url': '?report_type=campaign_performance'},
        {'name': 'Rapport de Suivi des Interactions', 'url': '?report_type=interaction'},
        {'name': 'Voir Historique des Rapports', 'url': '?action=history'},
    ]
    return render(request, 'reports/report_dashboard.html', {'report_options': report_options})

def export_data(request, format='excel'):
    if format == 'excel':
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Leads"
        ws.append(["ID", "Prénom", "Nom", "Statut", "Date"])

        for lead in Lead.objects.all():
            date_naive = lead.date_creation.replace(tzinfo=None) if lead.date_creation else None
            ws.append([lead.id, lead.prenom, lead.nom, lead.statut, date_naive])
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename="leads.xlsx"'
        wb.save(response)
        return response

    elif format == 'pdf':
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        p.drawString(100, height - 100, "Leads Report")
        y = height - 120

        for lead in Lead.objects.all():
            date_naive = lead.date_creation.replace(tzinfo=None) if lead.date_creation else None
            p.drawString(100, y, f"ID: {lead.id}, Prénom: {lead.prenom}, Nom: {lead.nom}, Statut: {lead.statut}, Date: {date_naive}")
            y -= 20

        p.showPage()
        p.save()
        buffer.seek(0)
        response = HttpResponse(buffer, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="leads.pdf"'
        return response
    else:
        return HttpResponse("Format non supporté", status=400)

Cenv/Projet/templates/reports/report_dashboard.html
{%include 'parts/nav.html'%}

<!DOCTYPE html>
<html>
<head>
    <title>Tableau de Bord des Rapports</title>
    <style>
        .right-left {
            background-color: #F6F2F2; 
            border-radius: 15px;
            height: 100%;
            width: 81%;
            position: absolute;
            top: 131px;
            left: 17.5%;
            overflow: hidden;
            box-shadow: 
                2px 2px 5px rgba(0, 0, 0, 0.2), /* Première ombre */
                4px 4px 10px rgba(0, 0, 0, 0.4), /* Deuxième ombre */
                6px 6px 15px rgba(0, 0, 0, 0.6); /* Troisième ombre */
        }
        .right-side-desous {
            position: relative;
            top: 23px;
            left: 12px;
        }
        .right-side-desous li {
            list-style-type: none;
        }
        .right-side-desous a {
            text-decoration: none;
        }

        /***cards div***/
        .ag-courses_box {
            display: inline-block;
            flex-wrap: wrap;
            padding: 10px 0; /* Réduit le padding pour réduire l'espace global autour des cartes */
            justify-content: space-between; /* Ajuste la distribution des cartes dans le conteneur */
        }

        .ag-courses_item {
            width: 360px;
            flex-basis: calc(30% - 30px); /* Réduit la largeur des cartes à 30% */
            margin: 0 15px 30px;
            overflow: hidden;
            border-radius: 28px;
        }

        .ag-courses-item_link {
          background-color: #121212;
            display: block;
            overflow: hidden;
            position: relative;
            text-decoration: none;
            padding: 22px 20px; /* Augmente la hauteur des cartes en ajustant le padding */
        }

        .ag-courses-item_title {
            min-height: 87px;
            margin: 0 0 25px;
            overflow: hidden;
            font-weight: bold;
            font-size: 30px;
            color: #FFF;
            z-index: 2;
            position: relative;
        }

        .ag-courses-item_link:hover {
            color: #FFF;
            text-decoration: none;
        }

        .ag-courses-item_link:hover .ag-courses-item_bg {
            -webkit-transform: scale(10);
            -ms-transform: scale(10);
            transform: scale(10);
        }

        .ag-courses-item_bg {
            height: 128px;
            width: 128px;
            background-color: #f9b234;
            z-index: 1;
            position: absolute;
            top: -75px;
            right: -75px;
            border-radius: 50%;
            transition: all .5s ease;
        }

        .card-color-1 .ag-courses-item_bg {
            background-color: #f9b234; /* Couleur pour la première carte */
        }

        .card-color-2 .ag-courses-item_bg {
            background-color: #3ecd5e; /* Couleur pour la deuxième carte */
        }

        .card-color-3 .ag-courses-item_bg {
            background-color: #e44002; /* Couleur pour la troisième carte */
        }
        
        .card-color-4 .ag-courses-item_bg {
            background-color:  #952aff; /* Couleur pour la troisième carte */
        }
        .hidden {
            display: none;
        }

        .visible {
            display: block;
        }
        .h22{
        margin-left: 12px;
        margin-bottom: 34px;
        font-style: Abhaya Libre ExtraBold;
        }
    </style>
</head>
<body>
    <div class="left-side">
        {% include 'parts/button.html' %}
    </div>

    <div class="right-left">
        <div class="right-side-desous">
            <h1 class="h22">Tableau de Bord des Rapports</h1>

            {% if report_options %}
                <div class="div-card">
                    {% for option in report_options %}
                        <div class="ag-courses_box">
                            <div class="ag-courses_item card-color-{{ forloop.counter }}">
                                <a href="{% url 'report_dashboard' %}{{ option.url }}" class="ag-courses-item_link">
                                    <div class="ag-courses-item_bg"></div>
                                    <div class="ag-courses-item_title">{{ option.name }}</div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            {% if form %}
                <h2>{{ report_type }}</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Générer ce Rapport</button>
                </form>
            {% endif %}

            {% if reports %}
                <h2 class="h22">Historique des Rapports</h2>
                <ul>
                    {% for report in reports %}
                        <li>
                            <a href="{% url 'report_detail' report.id %}">{{ report.title }}</a> |
                            <a href="{% url 'report_detail' report.id %}?export=pdf">Exporter en PDF</a> |
                            <a href="{% url 'report_detail' report.id %}?export=excel">Exporter en Excel</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            <h2>Exporter les Données</h2>
            <ul>
                <li><a href="{% url 'export_data' 'excel' %}">Exporter les Leads en Excel</a></li>
                <li><a href="{% url 'export_data' 'pdf' %}">Exporter les Leads en PDF</a></li>
            </ul>
        </div>
    </div>
</body>
</html>

Cenv/Projet/templates/reports/report_detail.html
{% include 'parts/nav.html' %}

<!DOCTYPE html>
<html>
<head>
    <title>Détails du Rapport</title>
    <style>
        .right-side {
            background-color: #F6F2F2; 
            border-radius: 15px;
            height: 100%;
            width: 81%;
            position: absolute;
            top: 131px;
            left: 17.5%;
            overflow: hidden;
            box-shadow: 
                2px 2px 5px rgba(0, 0, 0, 0.2), /* Première ombre */
                4px 4px 10px rgba(0, 0, 0, 0.4), /* Deuxième ombre */
                6px 6px 15px rgba(0, 0, 0, 0.6); /* Troisième ombre */
        }
    </style>
</head>
<body>
    <div class="left-side">
        {% include 'parts/button.html' %}
    </div>
    <div class="right-side">
        <h1>{{ report.title }}</h1>
        <p><strong>Type de Rapport :</strong> {{ report.get_report_type_display }}</p>
        <p><strong>Créé par :</strong> {{ report.created_by }}</p>
        <p><strong>Date de Création :</strong> {{ report.created_at }}</p>
        <h2>Contenu :</h2>
        <pre>{{ report.content }}</pre>
        <a href="{% url 'report_dashboard' %}">Retour au tableau de bord</a>
    </div>
</body>
</html>

Cenv/Projet/templates/reports/report_form.html
{% include 'parts/nav.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Créer un Rapport</title>
    <style>
        .right-side {
            background-color: #F6F2F2;
            border-radius: 15px;
            height: 100%;
            width: 81%;
            position: absolute;
            top: 131px;
            left: 17.5%;
            overflow: auto;
            box-shadow: 
                2px 2px 5px rgba(0, 0, 0, 0.2),
                4px 4px 10px rgba(0, 0, 0, 0.4),
                6px 6px 15px rgba(0, 0, 0, 0.6);
        }

        .right-side-desous {
            padding: 20px;
        }

        .right-side-desous img {
            height: 240px;
            width: 520px;
            display: block;
            margin: 0 auto;
            position: relative;
            left: 20px;
            top: -20px;
        }

        .right-side-desous-form {
            text-align: center;
            margin-top: 20px;
        }

        .right-side-desous-form h1 {
            color: #3B4582;
            margin-bottom: 20px;
            margin-right: 10px;
            margin-top: -40px;
        }

        .right-side-desous-form form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .right-side-desous-form form input,
        .right-side-desous-form form textarea,
        .right-side-desous-form form select {
            padding: 8px;
            width: 400px; /* Largeur unifiée */
            margin-bottom: 10px;
        }

        .right-side-desous-form form label {
            font-size: 18px;
            font-weight: 600; /* Retirer le 'px' */
            /* Affichage en bloc */
            margin-bottom: 5px; /* Espacement sous le label */
        }

        .right-side-desous-form button {
            padding: 10px 20px;
            background-color: #3B4582;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        .right-side-desous-form a {
            display: block;
            margin-top: 20px;
            color: #3B4582;
            text-decoration: none;
        }

        .right-side-desous-form a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="left-side">
        {% include 'parts/button.html' %}
    </div>

    <div class="right-side">
        <div class="right-side-desous">
            {% load static %}
            <img src="{% static 'images/img11.jpg' %}" alt="Image" />
            <div class="right-side-desous-form">      
                <h1>Créer un Rapport</h1>
                <form method="post">
                    {% csrf_token %}
                    
                    <label for="id_title">Titre</label>
                    {{ form.title }}

                    <label for="id_content">Contenu</label>
                    {{ form.content }}

                    <label for="id_report_type">Type de Rapport</label>
                    {{ form.report_type }}

                    <label for="id_start_date">Date de Début</label>
                    {{ form.start_date }}

                    <label for="id_end_date">Date de Fin</label>
                    {{ form.end_date }}

                    <label for="id_category">Catégorie</label>
                    {{ form.category }}

                    <button type="submit">Générer ce Rapport</button>
                </form>
                <a href="{% url 'report_dashboard' %}">Retour au tableau de bord</a>
            </div>
        </div>
    </div>
</body>
</html>

Cenv/Projet/templates/reports/report_history.html
{% include 'parts/nav.html' %}

<!DOCTYPE html>
<html>
<head>
    <title>Historique des Rapports</title>
    <style>
        .right-side {
            background-color: #F6F2F2;
            border-radius: 15px;
            height: 100%;
            width: 81%;
            position: absolute;
            top: 131px;
            left: 17.5%;
            overflow: hidden;
            box-shadow: 
                2px 2px 5px rgba(0, 0, 0, 0.2), 
                4px 4px 10px rgba(0, 0, 0, 0.4), 
                6px 6px 15px rgba(0, 0, 0, 0.6);
        }
    </style>
</head>
<body>
    <div class="left-side">
        {% include 'parts/button.html' %}
    </div>

    <div class="right-side">
        <h1>Historique des Rapports</h1>
        <ul>
            {% for report in reports %}
                <li><a href="{% url 'report_detail' report.id %}">{{ report.title }}</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'report_dashboard' %}">Retour au tableau de bord</a>
    </div>
</body>
</html>